apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: application-platform.neptunus.thomasvitale.com.0.1.0
spec:
  refName: application-platform.neptunus.thomasvitale.com
  version: 0.1.0
  releaseNotes: "Initial platform configuration"
  releasedAt: 2022-06-26T21:30:00Z
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/application-platform@sha256:4e065e4781c7f5010aad99a21706abd73f230e479f1dd6dde11859c66df67799
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
