apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: namespace-setup.neptunus.thomasvitale.com.0.1.3
spec:
  refName: namespace-setup.neptunus.thomasvitale.com
  version: 0.1.3
  releaseNotes: "Initial namespace setup"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/namespace-setup@sha256:6f3d977e4ef92168f43947e6faf279a50e7d14d00c818898006ce1f117d0a1c5
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
