apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: tekton-pipelines.neptunus.thomasvitale.com
spec:
  displayName: "tekton-pipelines"
  longDescription: "A cloud native solution for building CI/CD pipelines."
  shortDescription: "CI/CD tool."
  providerName: Neptunus Platform
  maintainers:
    - name: Thomas Vitale
  categories:
    - ci/cd
