apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cartographer-blueprints.neptunus.thomasvitale.com.0.0.2
spec:
  refName: cartographer-blueprints.neptunus.thomasvitale.com
  version: 0.0.2
  releaseNotes: "Initial collection of blueprints"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/cartographer-blueprints@sha256:c22bea28f5ccaa43e1ab16220d94de11e43d87b0ce529716ad5f426ec316ddb3
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
