apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tekton-pipelines.neptunus.thomasvitale.com.0.36.0
spec:
  refName: tekton-pipelines.neptunus.thomasvitale.com
  version: 0.36.0
  releaseNotes: "Tekton Pipelines 0.36.0 https://github.com/tektoncd/pipeline/releases/tag/v0.36.0"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/package-for-tekton-pipelines@sha256:22fe15f0a01ee4147aec7591f788e7b0d9deba394570f3c82f8867e13de032f7
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
