apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: application-platform.neptunus.thomasvitale.com.0.0.10
spec:
  refName: application-platform.neptunus.thomasvitale.com
  version: 0.0.10
  releaseNotes: "Initial platform configuration"
  releasedAt: 2022-06-26T21:30:00Z
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/application-platform@sha256:d4b12d2283b6d7b9f42cefaa1a335aeb48994536c241cb8359c55d232a8ef3be
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
