apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: application-platform.neptunus.thomasvitale.com.0.0.3
spec:
  refName: application-platform.neptunus.thomasvitale.com
  version: 0.0.3
  releaseNotes: "Initial platform configuration"
  releasedAt: 2022-06-26T21:30:00Z
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/application-platform@sha256:ce910999c255777c9885120c9af296f75da7097a936d272f3185db7715fa9839
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
