apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: application-platform.neptunus.thomasvitale.com.0.0.2
spec:
  refName: application-platform.neptunus.thomasvitale.com
  version: 0.0.2
  releaseNotes: "Initial platform configuration"
  releasedAt: 2022-06-26T21:30:00Z
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/application-platform@sha256:7b6e8714d1136ce54f0af037ce913dd9c4a19113f889587f5a4be8cd5e398d99
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
