apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cartographer-blueprints.neptunus.thomasvitale.com.0.0.4
spec:
  refName: cartographer-blueprints.neptunus.thomasvitale.com
  version: 0.0.4
  releaseNotes: "Initial collection of blueprints"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/cartographer-blueprints@sha256:3ccf6b3a72f1b5797ccb898f5607d2e5cd5045144c0bfbcb20fbab4492d110a4
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
