apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cartographer-catalog.neptunus.thomasvitale.com.0.0.2
spec:
  refName: cartographer-catalog.neptunus.thomasvitale.com
  version: 0.0.2
  releaseNotes: "Initial supply chains"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/cartographer-catalog@sha256:a0fe4937fa5ec4aac3ff0d71eba0f8d5889a3f7c0cb9d5d891eaeda2a079f2f2
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
