apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: knative-eventing.neptunus.thomasvitale.com.1.5.1
spec:
  refName: knative-eventing.neptunus.thomasvitale.com
  version: 1.5.1
  releaseNotes: "Knative Eventing 1.5.1 https://github.com/knative/eventing/releases/tag/knative-v1.5.1"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/package-for-knative-eventing:sha256-c2793e24df5cc75f12dbf47ec8f9e1dbf904ddd284dd5f7e44a275cc26f1b20e.imgpkg
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
