apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: argo-cd.neptunus.thomasvitale.com.2.4.6
spec:
  refName: argo-cd.neptunus.thomasvitale.com
  version: 2.4.6
  releaseNotes: "Argo CD 2.4.6 https://github.com/argoproj/argo-cd/releases/tag/v2.4.6"
  releasedAt: 2022-07-15T20:30:00Z
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: ghcr.io/neptunus-platform/package-for-argo-cd@sha256:65ebc906e08256c45eaf59801521f7e9752681ad422eda931289d437bda3bcc5
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}
